let checklistData = {
  code: '0',
  msg: '',
  data: [{
    id: 1,
    name: '人員衛生',
    items: [{
      id: 1,
      name: '員工著裝、穿戴情況',
      totalCount: 100,
      checkedCount: 100,
      passedCount: 65,
      unpassedCount: 35
    }, {
      id: 2,
      name: '私人物品禁入廚房的情況',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 3,
      name: '員工在廚房內的不良衛生行為',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }, {
    id: 2,
    name: '環境',
    items: [{
      id: 4,
      name: '地面、牆面、水溝、門窗的衛生狀況',
      totalCount: 100,
      checkedCount: 100,
      passedCount: 85,
      unpassedCount: 15
    }]
  }, {
    id: 3,
    name: '貯存設施',
    items: [{
      id: 5,
      name: '雪櫃溫度的符合性',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 6,
      name: '貯存設施的衛生狀況',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }, {
    id: 4,
    name: '貯存管理',
    items: [{
      id: 7,
      name: '標籤標識管理情況',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 8,
      name: '食品的貯存條件',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 9,
      name: '食品的分類貯存',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 10,
      name: '食品的防護情況',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 11,
      name: '食品的先進先出及保質期管理情況',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }, {
    id: 5,
    name: '測試名字過長測試名字過長測試名字過長',
    items: [{
      id: 12,
      name: '測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 13,
      name: '測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }]
};

let entityData = {
  code: '0',
  msg: '',
  data: [{
    id: 1,
    name: '人員',
    items: [{
      id: 1,
      name: '員工1',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 2,
      name: '員工2',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 3,
      name: '員工3',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }, {
    id: 2,
    name: '環境',
    items: [{
      id: 4,
      name: '地面',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 5,
      name: '墻面',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 6,
      name: '水溝',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 7,
      name: '門窗',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }, {
    id: 3,
    name: '貯存設施',
    items: [{
      id: 8,
      name: '雪櫃1',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 9,
      name: '雪櫃2',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 10,
      name: '雪櫃3',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 11,
      name: '雪櫃4',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }, {
    id: 4,
    name: '測試名字過長測試名字過長測試名字過長',
    items: [{
      id: 12,
      name: '測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 13,
      name: '測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }, {
    id: 5,
    name: '測試测试測試测试',
    items: [{
      id: 14,
      name: '測試测试測試测试測試测试測試测试測試测试測試测试',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 15,
      name: '測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }, {
    id: 6,
    name: '測試测试測試测试',
    items: [{
      id: 16,
      name: '測試测试測試测试測試测试測試测试測試测试測試测试',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 17,
      name: '測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }, {
    id: 7,
    name: '測試测试測試测试',
    items: [{
      id: 18,
      name: '測試测试測試测试測試测试測試测试測試测试測試测试',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }, {
      id: 19,
      name: '測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長測試名字過長',
      totalCount: 100,
      checkedCount: 80,
      passedCount: 65,
      unpassedCount: 15
    }]
  }]
};

export {
  checklistData,
  entityData
};